---
# neutron quotas must be set in neutron.conf with puppet!
# https://github.com/norcams/himlar/blob/master/hieradata/common/modules/neutron.yaml
cinder:
  backup_gigabytes:             1000
  backups:                      10
  gigabytes:                    100
  per_volume_gigabytes:         -1
  snapshots:                    12
  volumes:                      4
nova:
  instances:                    2
  cores:                        4
  ram:                          8192
  injected_file_content_bytes:  10240
  injected_file_path_bytes:     255
  injected_files:               5
  key_pairs:                    100
  metadata_items:               128
