---
nova:
  instances:                    20
  cores:                        40
  ram:                          65536
cinder:
  gigabytes:                    200
  snapshots:                    40
  volumes:                      20
neutron:
  security_group:               40
  security_group_rule:          400
