---
type: 'gold'
images:
  'ubuntu_1604':
    'name':             'GOLD Ubuntu 16.04 LTS'
    'depricated':       'Outdated (Ubuntu)'
    'url':              'http://builder/'
    'latest':           'ubuntu_1604-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'ubuntu_1804':
    'name':             'GOLD Ubuntu 18.04 LTS'
    'depricated':       'Outdated (Ubuntu)'
    'url':              'http://builder/'
    'latest':           'ubuntu_1804-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'centos6':
    'name':             'GOLD CentOS 6'
    'depricated':       'Outdated (CentOS)'
    'url':              'http://builder/'
    'latest':           'centos6-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'centos7':
    'name':             'GOLD CentOS 7'
    'depricated':       'Outdated (CentOS)'
    'url':              'http://builder/'
    'latest':           'centos7-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'debian9':
    'name':             'GOLD Debian 9'
    'depricated':       'Outdated (Debian)'
    'url':              'http://builder/'
    'latest':           'debian9-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'fedora_27':
    'name':             'GOLD Fedora 27'
    'depricated':       'Outdated (Fedora)'
    'url':              'http://builder/'
    'latest':           'fedora_27-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'fedora_28':
    'name':             'GOLD Fedora 28'
    'depricated':       'Outdated (Fedora)'
    'url':              'http://builder/'
    'latest':           'fedora_28-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
      'hw_rng_model':   'virtio'
  'winsrv2016std':
    'name':             'GOLD Windows Server 2016 Standard'
    'depricated':       'Outdated (Windows)'
    'url':              'http://genisys.uib.no/images/'
    'latest':           'win2016-server.qcow2'
    'min_ram':          4090
    'min_disk':         39
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
