---
type: 'gold'
images:
  'ubuntu_1604':
    'name':             'NEW GOLD Ubuntu server 16.04'
    'depricated':       'Outdated (Ubuntu)'
    'url':              'http://builder/'
    'latest':           'ubuntu_1604-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'debian8':
    'name':             'NEW GOLD Debian 8'
    'depricated':       'Outdated (Debian)'
    'url':              'http://builder/'
    'latest':           'debian8-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'debian9':
    'name':             'NEW GOLD Debian 9'
    'depricated':       'Outdated (Debian)'
    'url':              'http://builder/'
    'latest':           'debian9-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'centos6':
    'name':             'NEW GOLD CentOS 6'
    'depricated':       'Outdated (CentOS)'
    'url':              'http://builder/'
    'latest':           'centos6-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'centos7':
    'name':             'NEW GOLD CentOS 7'
    'depricated':       'Outdated (CentOS)'
    'url':              'http://builder/'
    'latest':           'centos7-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'fedora_25':
    'name':             'NEW GOLD Fedora 25'
    'depricated':       'Outdated (Fedora)'
    'url':              'http://builder/'
    'latest':           'fedora_25-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'fedora_26':
    'name':             'NEW GOLD Fedora 26'
    'depricated':       'Outdated (Fedora)'
    'url':              'http://builder/'
    'latest':           'fedora_26-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
