---
type: 'gold'
images:
  'ubuntu_1804':
    'name':             'GOLD Ubuntu 18.04 LTS'
    'depricated':       'Outdated (Ubuntu 18.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_1804-latest.qcow2'
    'builder_checksum': 'ubuntu_1804-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
  'ubuntu_2004':
    'name':             'GOLD Ubuntu 20.04 LTS'
    'depricated':       'Outdated (Ubuntu 20.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_2004-latest.qcow2'
    'builder_checksum': 'ubuntu_2004-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
  'ubuntu_2204':
    'name':             'GOLD Ubuntu 22.04 LTS'
    'depricated':       'Outdated (Ubuntu 22.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_2204-latest.qcow2'
    'builder_checksum': 'ubuntu_2204-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'hw_firmware_type':       'uefi'
      'os_require_quiesce':  'yes'
  'centos7':
    'name':             'GOLD CentOS 7'
    'depricated':       'Outdated (CentOS 7)'
    'url':              'http://builder/'
    'latest':           'centos7-latest.qcow2'
    'builder_checksum': 'centos7-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
  'centosstream8':
    'name':             'GOLD CentOS Stream 8'
    'depricated':       'Outdated (CentOS Stream 8)'
    'url':              'http://builder/'
    'latest':           'centosstream8-latest.qcow2'
    'builder_checksum': 'centosstream8-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':     'yes'
  'centosstream9':
    'name':             'GOLD CentOS Stream 9'
    'depricated':       'Outdated (CentOS Stream 9)'
    'url':              'http://builder/'
    'latest':           'centosstream9-latest.qcow2'
    'builder_checksum': 'centosstream9-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':     'yes'
  'almalinux8':
    'name':             'GOLD Alma Linux 8'
    'depricated':       'Outdated (Alma Linux 8)'
    'url':              'http://builder/'
    'latest':           'almalinux8-latest.qcow2'
    'builder_checksum': 'almalinux8-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':                'scsi'
      'hw_scsi_model':              'virtio-scsi'
      'hw_qemu_guest_agent':        'yes'
      'hw_machine_type':            'q35'
      'hw_firmware_type':           'uefi'
#      'hw_vif_multiqueue_enabled':  'yes'
      'os_require_quiesce':         'yes'
  'rockylinux8':
    'name':             'GOLD Rocky Linux 8'
    'depricated':       'Outdated (Rocky Linux 8)'
    'url':              'http://builder/'
    'latest':           'rockylinux8-latest.qcow2'
    'builder_checksum': 'rockylinux8-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':     'yes'
  'debian10':
    'name':             'GOLD Debian 10'
    'depricated':       'Outdated (Debian 10)'
    'url':              'http://builder/'
    'latest':           'debian10-latest.qcow2'
    'builder_checksum': 'debian10-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
  'debian11':
    'name':             'GOLD Debian 11'
    'depricated':       'Outdated (Debian 11)'
    'url':              'http://builder/'
    'latest':           'debian11-latest.qcow2'
    'builder_checksum': 'debian11-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'hw_firmware_type':       'uefi'
      'os_require_quiesce':     'yes'
  'fedora_36':
    'name':             'GOLD Fedora 36'
    'depricated':       'Outdated (Fedora 36)'
    'url':              'http://builder/'
    'latest':           'fedora_36-latest.qcow2'
    'builder_checksum': 'fedora_36-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_rng_model':           'virtio'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':     'yes'
