---
type: 'ipv6'
images:
  'ubuntu_1604':
    'name':             'IPv6 Ubuntu 16.04 LTS'
    'depricated':       'Outdated (Ubuntu)'
    'url':              'http://builder/ipv6/'
    'latest':           'ubuntu_1604-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'ubuntu_1710':
    'name':             'IPv6 Ubuntu 17.10'
    'depricated':       'Outdated (Ubuntu)'
    'url':              'http://builder/ipv6/'
    'latest':           'ubuntu_1710-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'centos6':
    'name':             'IPv6 CentOS 6'
    'depricated':       'Outdated (CentOS)'
    'url':              'http://builder/ipv6/'
    'latest':           'centos6-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'centos7':
    'name':             'IPv6 CentOS 7'
    'depricated':       'Outdated (CentOS)'
    'url':              'http://builder/ipv6/'
    'latest':           'centos7-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'debian9':
    'name':             'IPv6 Debian 9'
    'depricated':       'Outdated (Debian)'
    'url':              'http://builder/ipv6/'
    'latest':           'debian9-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'winsrv2016std':
    'name':             'IPv6 Windows Server 2016 Standard'
    'depricated':       'Outdated (Windows)'
    'url':              'http://genisys.uib.no/images/'
    'latest':           'win2016-server.qcow2'
    'min_ram':          4090
    'min_disk':         39
    'visibility':       'private'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
#  'fedora_26':
#    'name':             'IPv6 Fedora 26'
#    'depricated':       'Outdated (Fedora)'
#    'url':              'http://builder/ipv6/'
#    'latest':           'fedora_26-latest.qcow2'
#    'min_ram':          1024
#    'min_disk':         8
#    'visibility':       'private'
#    'properties':
#      'hw_disk_bus':    'scsi'
#      'hw_scsi_model':  'virtio-scsi'
