---
type: 'gold'
images:
  'fedora_27':
    'name':             'GOLD Fedora 27'
    'depricated':       'Outdated (Fedora)'
  'fedora_28':
    'name':             'GOLD Fedora 27'
    'depricated':       'Outdated (Fedora)'
