  'winsrv2016std':
    'name':             'GOLD Windows Server 2016 Standard'
    'depricated':       'Outdated Windows Server 2016 Standard (Windows)'
    'url':              'http://genisys.uib.no/images/'
    'latest':           'win2016-server-standard.qcow2'
    'checksum_file':    'win2016-server-standard.qcow2.sha256'
    'checksum':         'sha256'
    'min_ram':          4090
    'min_disk':         39
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'winsrv2019std':
    'name':             'GOLD Windows Server 2019 Standard'
    'depricated':       'Outdated Windows Server 2019 Standard (Windows)'
    'url':              'http://genisys.uib.no/images/'
    'latest':           'win2019-server-standard.qcow2'
    'checksum_file':    'win2016-server-standard.qcow2.sha256'
    'checksum':         'sha256'
    'min_ram':          4090
    'min_disk':         39
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
  'winsrv2019core':
    'name':             'GOLD Windows Server 2019 Core'
    'depricated':       'Outdated Windows Server 2019 Core (Windows)'
    'url':              'http://genisys.uib.no/images/'
    'latest':           'win2019-server-core.qcow2'
    'checksum_file':    'win2016-server-core.qcow2.sha256'
    'checksum':         'sha256'
    'min_ram':          4090
    'min_disk':         39
    'visibility':       'public'
    'properties':
      'hw_disk_bus':    'scsi'
      'hw_scsi_model':  'virtio-scsi'
