---
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 1000000
  hw_rng:rate_period: 60
  hw:cpu_policy: 'dedicated'
  hw:cpu_thread_policy: 'require'
  aggregate_instance_extra_specs:type: 's== atlas'
atlascpu:
  'atlascpu.2xlarge':
    vcpus: 8
    ram: 24576
    disk: 20
