---
public: false
c1: # (2x) new
  'c1.medium': # [1-2-20]
    vcpus: 1
    ram: 2
    disk: 20
  'c1.large': #  [2-4-20]
    vcpus: 1
    ram: 4
    disk: 20
  'c1.xlarge': # [4-8-20]
    vcpus: 4
    ram: 8
    disk: 20
  'c1.2xlarge': # [8-16-20]
    vcpus: 8
    ram: 16
    disk: 20
  'c1.4xlarge': # [16-32-20]
    vcpus: 16
    ram: 32
    disk: 20
  'c1.8xlarge': # [32-64-20]
    vcpus: 32
    ram: 64
    disk: 20
