---
public: false
d1:
  'd1.small':
    ram:    2048
    vcpus:  1
    disk:   20
  'd1.medium':
    ram:    4096
    vcpus:  2
    disk:   40
  'd1.large':
    ram:    8192
    vcpus:  4
    disk:   60
