---
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 2048
  hw_rng:rate_period: 1
  hw:mem_page_size: 2048
  aggregate_instance_extra_specs:type: 's== elixir'
elixir.m1a:
  'elixir.m1a.4xlarge':
    vcpus: 16
    ram: 61440
    disk: 20
  'elixir.m1a.8xlarge':
    vcpus: 32
    ram: 122880
    disk: 20
  'elixir.m1a.16xlarge':
    vcpus: 64
    ram: 245760
    disk: 20
  'elixir.m1a.32xlarge':
    vcpus: 128
    ram: 245758
    disk: 20
