---
public: true
m1:
  'm1.tiny':
    ram:    512
    disk:   1
    vcpus:  1
  'm1.small':
    ram:    2048
    vcpus:  1
    disk:   10
  'm1.medium':
    ram:    4096
    vcpus:  2
    disk:   20
  'm1.large':
    ram:    8192
    vcpus:  4
    disk:   20
