---
# public: false
# m2:
#   'm2.large':
#     ram:    8192
#     vcpus:  2
#     disk:   20
#   'm2.xlarge':
#     ram:    16384
#     vcpus:  4
#     disk:   20
#   'm2.2xlarge':
#     ram:    32768
#     vcpus:  8
#     disk:   20
#   'm2.4xlarge':
#     ram:    65536
#     vcpus:  16
#     disk:   20

public: false
m2: # (4x)
  'm2.2xlarge': # [8-32-20]
    vcpus: 8
    ram: 32
    disk: 20
  'm2.4xlarge': # [16-64-20]
    vcpus: 16
    ram: 64
    disk: 20
  'm2.8xlarge' : # [32-128-20] (new)
    vcpus: 32
    ram: 128
    disk: 20
