---
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 1000000
  hw_rng:rate_period: 60
# hw:numa_nodes: 1
  hw:cpu_sockets: 1
#  hw:cpu_policy: 'dedicated'
#  hw:cpu_thread_policy: 'require'
  aggregate_instance_extra_specs:type: 's== alice'
raytest:
  'raytest.xlarge':
    vcpus: 4
    ram: 15360
    disk: 10
  'raytest.2xlarge':
    vcpus: 8
    ram: 30720
    disk: 10
  'raytest.4xlarge':
    vcpus: 16
    ram: 61440
    disk: 10
