---
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 1000000
  hw_rng:rate_period: 60
  aggregate_instance_extra_specs:type: 's== alice'
  pci_passthrough:alias: 'isp2532:2'
tape:
  'tape.2xlarge':
    vcpus: 8
    ram: 32767
    disk: 20
  'tape.4xlarge':
    vcpus: 16
    ram: 65535
    disk: 20
