---
checks:
  access:
    ssl:  true
    host: 'access.dev.iaas.intern'
    url:  ''
    code: 200
  api:
    ssl:  true
    host: 'api.dev.iaas.intern:5000'
    url:  '/v3'
    code: 200
  dashboard:
    ssl:  true
    host: 'dashboard.dev.iaas.intern'
    url:  '/dashboard'
    code: 302
  network:
    ssl:  true
    host: 'network.api.dev.iaas.intern:9696'
    url:  '/'
    code: 200
  image:
    ssl:  true
    host: 'image.api.dev.iaas.intern:9292'
    url:  '/'
    code: 300
  volume:
    ssl:  true
    host: 'volume.api.dev.iaas.intern:8776'
    url:  '/'
    code: 300
  compute:
    ssl:  true
    host: 'compute.api.dev.iaas.intern:8774'
    url:  '/'
    code: 200
  identity:
    ssl:  true
    host: 'identity.api.dev.iaas.intern:5000'
    url:  '/'
    code: 300
