version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/himlar.log
    backupCount: 10
    when: h
root:
  level: DEBUG
  handlers: [console,file]
loggers:
  himlarcli:
    level: DEBUG
  requests:
    level: DEBUG
  keystoneclient:
    level: DEBUG
#  py.warnings:
#    handlers: [file]
