version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  console_format:
    format: '%(module)s.%(funcName)s():%(lineno)d %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: console_format
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/himlar.log
    backupCount: 30
    interval: 1
    when: d
root:
  level: DEBUG
  handlers: [console,file]
loggers:
  himlarcli:
    level: DEBUG
  requests:
    level: DEBUG
  keystoneclient:
    level: DEBUG
#  py.warnings:
#    handlers: [file]
