---
direction:
  - egress
remote_group_id: ["!None"]
remote_ip_prefix:
   - 2001:700:200::/48
   - 2001:700:100::/40
remote_ip_prefix_regex:
   - '129.177.[0-9]*.[0-9]*/[0-9]*'
   - '129.240.[0-9]*.[0-9]*/[0-9]*'
protocol:
  - ipv6-icmp
  - icmp
port:
  - 22
  - 80
  - 443
