---
uib:
  'server': 'ldap.uib.no'
  'base_dn': 'dc=uib,dc=no'
  'type': 'employeeType'
  'org': 'ou'
uio:
  'server': 'ldap.uio.no'
  'base_dn': 'dc=uio,dc=no'
  'type': 'eduPersonPrimaryAffiliation'
  'org': 'eduPersonPrimaryOrgUnitDN'
