---
uib:
  'server':   'ldaps://ldap.uib.no'
  'base_dn':  'dc=uib,dc=no'
  'type':     'employeeType'
  'org':      'ou'
uio:
  'server':   'ldaps://ldap.uio.no'
  'base_dn':  'dc=uio,dc=no'
  'type':     'eduPersonPrimaryAffiliation'
  'org':      'eduPersonPrimaryOrgUnitDN'
uia:
  'server':   'ldaps://ldap.uia.no'
  'base_dn':  'dc=uia,dc=no'
