---
desc:   'Fix admin'
actions:
  'list':     'List demo projects with missing admin'
  'update':   'Updated admin on demo prosjekt without admin'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
    'weight':   100
