---
desc:           'Manage host aggregate groups of compute nodes'
actions:
  'show':       'Show aggregate information'
  'instances':  'List instances in aggregate'
  'users':      'List users with instances in aggregate'
  'notify':     'Notify all users with instances in aggregate of migration'
  'migrate':    'Migrate all instances out of aggreate'
  'activate':   'Enable aggregate and disable all other aggregates'
opt_args:
  '-n':
    'dest':     'aggregate'
    'help':     'aggregate name'
    'required': True
    'metavar':  'name'
  '-m':
    'sub':      'notify'
    'dest':     'date'
    'help':     'date message'
    'metavar':  'date'
  '--stage':
    'sub':      'migrate'
    'dest':     'stage'
    'help':     'migration stage'
    'required': True
  '--limit':
    'sub':      'migrate'
    'type':     int
    'dest':     'limit'
    'help':     'number of instances to migrate before sleep'
    'default':  25
  '--sleep':
    'sub':      'migrate'
    'dest':     'sleep'
    'type':     int
    'help':     'number of seconds to sleep'
    'default':  180
  '--hard-limit':
    'sub':      'migrate'
    'dest':     'hard_limit'
    'action':   'store_const'
    'const':    true
    'help':     'exit script after migration of --limit instances'
    'default':  false
  '--host':
    'sub':      ['migrate','instances']
    'dest':     'host'
    'help':     'only use this host in the aggregate'
