---
desc:           'Script calculate and get billing information'
actions:
  'resources':    'Show resource usage for a project in a period (default period: last 1 day)'
  'flavors':      'Show flavor usage for a project in a period (default period: last 1 day)'
  'whales':       'List project usage for lagre projects'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  'project':
   'sub':       ['resources', 'flavors']
   'metavar':   'project'
  '--start':
    'sub':      ['resources', 'flavors', 'whales']
    'dest':     start
    'help':     'start date (YYYY-MM-DD) Defaults to yesterday'
  '--end':
    'sub':      ['resources', 'flavors', 'whales']
    'dest':     end
    'help':     'end date (YYYY-MM-DD) Defaults to today'
  '--threshold':
    'sub':      ['whales']
    'dest':     threshold
    'help':     'whales instances threshold'
    'default':  5
    'type':     int
  '--period':
    'sub':      ['resources', 'flavors']
    'dest':     period
    'help':     'report on usage'
    'default':  'total'
    'choices':  ['total', 'hourly', 'daily', 'monthly']
