---
# Use empty value for None
desc: 'Reclaim and remove instances. Use <action> -h for help on each action'
actions:
  'list':   'List instances for removal'
  'notify': 'Email users about instances for removal'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  '--region':
    'dest':     'region'
    'help':     'only use this region'
  '-t':
    'dest':     'type'
    'help':     'only instances from this project type'
  '-f':
    'dest':     'filter'
    'help':     'project filter'
