---
desc:   'Manage hypervisors/compute hosts'
actions:
  list:       'List all hypervisors'
  show:       'Show hypervisor details'
  instances:  'List all instances on hypervisor'
  move:       'Move host to another aggregate'
  enable:     'Enable hypervisor'
  disable:    'Disable hypervisor'
opt_args:
  'host':
    'sub':      ['move', 'show', 'instances', 'enable', 'disable']
    'metavar':  'host'
    'help':     'Hypervisor host. Use either hostname or FQDN'
  'aggregate':
    'sub':      ['move']
    'metavar':  'aggregate'
    'weight':   10
    'help':     'Aggreate name'
  '-t':
    'sub':      ['instances']
    'dest':     'type'
    'help':     'instance project type'
    'choices':  ['admin', 'demo', 'personal', 'research', 'education', 'course', 'test', 'hpc']
  '-a':
    'sub':      ['list']
    'dest':     aggregate
    'default':  'all'
    'help':     Limit list to one aggregate
