---
# Use empty value for None
desc: 'Manage gold images. Use <action> -h for help on each action'
actions:
  'list':     'List all active gold images (public)'
  'update':   'Update images from config file'
  'usage':    'Check image usage'
  'purge':    'Delete images'
opt_args:
  '--region':
    'dest':     'region'
    'help':     'override current region'
  '-i':
    'sub':      'update'
    'dest':     'image_config'
    'help':     'config file under config/images/'
    'default':  'gold.yaml'
  '-n':
    'sub':      'update'
    'dest':     'name'
    'help':     'only use image with this name'
  '-t':
    'sub':      ['update', 'usage', 'purge']
    'dest':     'type'
    'help':     'image type'
    'default':  'gold'
  '-v':
    'sub':      ['usage', 'purge']
    'dest':     'visibility'
    'help':     'image visibility'
  '--deactive':
    'sub':      ['usage', 'purge']
    'dest':     'deactive'
    'help':     'only deactivated images'
    'action':   'store_const'
    'const':    true
    'default':  false
