---
# Use empty value for None
desc: 'Manage gold images. Use <action> -h for help on each action'
actions:
  'list':     'List all active gold images (public)'
  'update':   'Update images from config file'
  'usage':    'Check image usage'
  'purge':    'Delete images'
  'grant':    'Grant access to private image from project'
opt_args:
  '--region':
    'dest':     'region'
    'help':     'override current region'
  '--domain':
    'sub':      'grant'
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  '--detailed':
    'sub':      'list'
    'dest':     'detailed'
    'help':     'show detailed list'
    'action':   'store_const'
    'const':    true
    'default':  false
  '-i':
    'sub':      'update'
    'dest':     'image_config'
    'help':     'config file under config/images/'
    'default':  'gold.yaml'
  '-n':
    'sub':      ['update', 'grant']
    'dest':     'name'
    'help':     'only use image with this name'
  '-t':
    'dest':     'type'
    'help':     'image type'
    'default':  'gold'
    'choices':  ['all', 'gold']
  '-p':
    'sub':      'grant'
    'dest':     'project'
    'help':     'project name to grant access to'
  '-v':
    'sub':      ['usage', 'purge', 'list']
    'dest':     'visibility'
    'help':     'image visibility'
    'default':  'public'
    'choices':  ['public', 'private']
  '--deactive':
    'sub':      ['usage', 'purge', 'list']
    'dest':     'deactive'
    'help':     'only deactivated images'
    'action':   'store_const'
    'const':    true
    'default':  false
