---
# Use empty value for None
desc: 'Manage images in current region! Use <action> -h for help on each action'
actions:
  'list':         'List all images. Output depends on visibility, tags and status'
  'update':       'Update images from config file'
  'usage':        'Check image usage. Output depends on visibility, tags and status'
  'purge':        'Delete unused deactive images'
  'grant':        'Grant access to a shared image'
  'revoke':       'Revoke access to a shared image'
  'list-access':  'List project with access to shared images'

opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
    'weight':   60
  '--detailed':
    'sub':      ['usage']
    'dest':     'detailed'
    'help':     'show detailed list'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--skip-cleanup':
    'sub':      ['update']
    'dest':     'skip_cleanup'
    'help':     'skip cleanup of downloaded images'
    'action':   'store_const'
    'const':    true
    'default':  false
  '-i':
    'sub':      ['update']
    'dest':     'image_config'
    'help':     'config file under config/images/'
    'default':  'default.yaml'
  '-s':
    'sub':      ['list', 'usage']
    'dest':     'status'
    'help':     'image status'
    'default':  'active'
    'choices':  ['acitve', 'deactive']
  '-v':
    'sub':      ['list', 'usage', 'purge']
    'dest':     'visibility'
    'help':     'image visibility'
    'default':  'public'
    'choices':  ['public', 'private', 'shared']
  '-t':
    'sub':      ['list', 'usage', 'purge', 'grant', 'revoke', 'list-access']
    'dest':     'type'
    'help':     'image type tag'
    'default':  'all'
  '-n':
    'sub':      ['list', 'usage', 'purge', 'update', 'grant', 'revoke', 'list-access']
    'dest':     'name'
    'help':     'image name tag (short name)'
  '-p':
    'sub':      ['grant', 'revoke']
    'dest':     'project'
    'help':     'project name to grant image access'
    'required': true
  '--limit':
    'sub':      ['purge']
    'dest':     'limit'
    'help':     'limit number of deleted images'
