---
desc: 'Perform action on node (use short nodename without region or domain)'
actions:
  'install':   'install a new node'
  'reinstall': 'reinstall new node'
  'delete':    'delete a node'
  'show':      'show node info'
  'list':      'list all nodes'
  'full':      'install all nodes'
opt_args:
  '-n':
    'sub':      ['show', 'install', 'delete', 'reinstall']
    'dest':     'node'
    'metavar':  'nodename'
    'help':     'location part can be dropped, eg. compute-01'
    'required': true
  '-y':
    'sub':      ['reinstall', 'delete']
    'dest':     'assume_yes'
    'help':     'assume yes when deleting a node (for automation purposes)'
    'action':   'store_const'
    'const':    true
    'default':  false
  '-e':
    'sub':      ['reinstall']
    'dest':     'sensu_expire'
    'help':     'silence sensu for a given period of time (in seconds)'
