---
desc:   'Project management for UH-IaaS'
actions:
  'list':   'List project. Use -f to filter result by project type'
  'show':   'Show all attributes for a project'
  'create': 'Create a new project and grant admin access if valid user'
  'grant':  'Grant access to project for user.'
  'delete': 'Delete project and all resources'
#  'update': 'TODO'
#  'revoke': 'TODO'
#  'instances': 'TODO list all instances in project'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  'project':
   'sub':       ['show', 'create', 'grant', 'delete']
   'metavar':   'project'
  '--region':
    'sub':      ['show', 'create']
    'dest':     'region'
    'help':     'specify region'
  '--end':
    'sub':      ['create']
    'dest':     'enddate'
    'help':     'set end date for projects (DD.MM.YYYY)'
  '-f':
    'sub':      ['list']
    'dest':     'filter'
    'help':     'filter by project type'
    'default':  'all'
    'choices':  ['all', 'admin', 'demo', 'personal', 'research', 'education', 'course', 'test']
  '-a':
    'sub':      ['create']
    'dest':     'admin'
    'help':     'email for admin user (can be non openstack user)'
    'required': true
  '-t':
    'sub':      ['create']
    'dest':     'type'
    'help':     'project type'
    'choices':  ['admin', 'demo', 'personal', 'research', 'education', 'course', 'test']
    'required': true
  '--desc':
    'sub':      ['create']
    'dest':     'desc'
    'metavar':  'description'
    'help':     'project project description'
  '-q':
    'sub':      ['create']
    'dest':     'quota'
    'help':     'quota class'
    'choices':  ['small', 'medium', 'large']
  '-u':
    'sub':      ['grant']
    'dest':     'user'
    'help':     'email of valid openstack user'
    'required': true
  '--force':
    'sub':      ['delete']
    'dest':     'force'
    'help':     'delete project without question'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--detailed':
    'sub':      ['show']
    'dest':     'detailed'
    'help':     'also show roles and quota for project'
    'action':   'store_const'
    'const':    true
    'default':  False
  '--rt':
    'sub':      ['create']
    'dest':     'rt'
    'metavar':  'request tracker ticket'
    'help':     'rt ticket number or link'
