---
desc: 'Publish status message to Slack, Twitter and UH-IaaS status backend'
actions:
  important: 'Publish to Slack, Twitter and UH-IaaS status backend (tagged important)'
  news:      'Publish to Slack, Twitter and UH-IaaS status backend (tagged info)'
  info:      'Publish to Twitter and UH-IaaS status backend (tagged info)'
  event:     'Publish to UH-IaaS event backend'
opt_args:
  '-t':
    'dest':     'template'
    'help':     'Message body template file, eg. notify/notify_maintenance.txt'
  '-m':
    'dest':     'message'
    'help':     'Message body as a command-line argument (overrides -t option if both are given)'
  '-r':
    'dest':     'region'
    'help':     'Region to substitute $region in template (automatically uppercased)'
    'choices':  ['osl', 'bgo', 'tos']
  '-d':
    'dest':     'date'
    'help':     'Date to substitute $date in template (as written, will NOT be parsed!)'
  '-l':
    'sub':      ['important']
    'dest':     'link'
    'help':     'Link to status.uh-iaas.no on important Slack and Twitter messages'
    'action':   'store_const'
    'const':    true
    'default':  false

