---
desc: 'Publish status message to Slack, Twitter and UH-IaaS status backend'
actions:
  important: 'Publish to Slack, Twitter and UH-IaaS status backend (tagged important)'
  info:      'Publish to Twitter and UH-IaaS status backend (tagged info)'
opt_args:
  '-t':
    'dest':     'template'
    'help':     'Message body template file, eg. misc/notify_maintenance.txt'
  '-m':
    'dest':     'message'
    'help':     'Message body as a command-line argument (overrides -t option if both are given)'
  '-r':
    'dest':     'region'
    'help':     'Region to substitute $region in template (automatically uppercased)'
    'choices':  ['osl', 'bgo', 'tos']
  '-d':
    'dest':     'date'
    'help':     'Date to substitute $date in template (as written, will NOT be parsed!)'
