---
desc: 'Manage default quota'
actions:
  'update': 'Update default quota'
  'show':   'Show default quota'
opt_args:
  '--region':
    'dest':     'region'
    'help':     'only use this region'
  '-n':
    'dest':     'service'
    'metavar':  'service type'
    'help':     'openstack service type'
    'choices':  ['all', 'nova', 'cinder']
    'default':  'all'
  '--default':
    'sub':      'update'
    'dest':     'quota_config'
    'help':     'config file under config/quotas/'
    'default':  'default.yaml'
#  '--domain':
#    'dest':     'domain'
#    'help':     'openstack domain to use'
#    'default':  'Dataporten'
