---
desc:       'Misc stats for OS-disk storage migration'
actions:
  'disabled':  'Show instances in disabled project'
  'nodiscard': 'Show instances without image with discard support'
opt_args: {}
