---
# Use empty value for None
desc: 'Manage our users. Use <action> -h for help on each action'
actions:
  'list':   'List of users and show stats based on email domain'
  'show':   'Show user information'
  'delete': 'Delete user. FIXME: NOT WORKING!'
  'rename': 'Use this when user changes affiliation'
opt_args:
  '-n':
    'sub':      'show'
    'dest':     'user'
    'help':     'existing user email (case sensitive)'
    'required': true
  '--new':
    'sub':      'rename'
    'dest':     'new'
    'help':     'new user email (case sensitive)'
    'metavar':  'user'
    'required': true
  '--old':
    'sub':      'rename'
    'dest':     'old'
    'help':     'old user email (case sensitive)'
    'metavar':  'user'
    'required': true
  '-o':
    'sub':      'show'
    'dest':     'obj_type'
    'metavar':
    'help':     'user object type to show'
    'choices':   ['api', 'dataporten', 'group', 'projects']
    'default': 'projects'
