---
# Use empty value for None
desc: 'Manage our users. Use <action> -h for help on each action'
actions:
  'list':     'List of users and show stats based on email domain'
  'show':     'Show user information'
  'delete':   'Delete user'
  'rename':   'Use this when user changes affiliation'
  'password': 'Reset API password for user'
opt_args:
  '-n':
    'sub':      ['show', 'password', 'delete']
    'dest':     'user'
    'help':     'existing user email (case sensitive)'
    'required': true
    'metavar':  'username'
  '--new':
    'sub':      'rename'
    'dest':     'new'
    'help':     'new user email (case sensitive)'
    'metavar':  'user'
    'required': true
  '--old':
    'sub':      'rename'
    'dest':     'old'
    'help':     'old user email (case sensitive)'
    'metavar':  'user'
    'required': true
  '-o':
    'sub':      'show'
    'dest':     'obj_type'
    'metavar':
    'help':     'user object type to show'
    'choices':   ['api', 'dataporten', 'group', 'projects']
    'default':  'projects'
