nodes:
  access-01:
    compute_profile: 1
    compute_resource: controller-03
  api-01:
    compute_profile: 1
    compute_resource: controller-01
  builder-01:
    compute_profile: 2
    compute_resource: controller-04
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'masstorage'
          capacity:     '50G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  cephmon-01:
    compute_profile: 2
    compute_resource: controller-01
  cephmon-02:
    compute_profile: 2
    compute_resource: controller-02
  cephmon-03:
    compute_profile: 2
    compute_resource: controller-03
  compute-01:
    mac: ec:f4:bb:ce:21:84
  compute-02:
    mac: ec:f4:bb:cd:a0:94
  compute-03:
    mac: ec:f4:bb:cd:a0:2c
  compute-04:
    mac: 18:66:da:82:7e:a8
  compute-05:
    mac: 18:66:da:82:b5:49
  compute-06:
    mac: 18:66:da:82:be:7a
  compute-07:
    mac: 00:0a:f7:79:c5:df
  compute-08:
    mac: 00:0a:f7:79:c5:e3
  compute-09:
    mac: 00:0a:f7:82:54:23
  compute-10:
    mac: 00:0a:f7:79:c5:f3
  console-01:
    compute_profile: 2
    compute_resource: controller-03
  controller-01:
    mac: ec:f4:bb:cc:ce:f4
  controller-02:
    mac: ec:f4:bb:cc:d1:54
  controller-03:
    mac: ec:f4:bb:cc:d0:9c
  controller-04:
    mac: b0:83:fe:e8:3a:31
  dashboard-01:
    compute_profile: 3
    compute_resource: controller-02
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '60G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  db-01:
    compute_profile: 1
    compute_resource: controller-01
  db-02:
    compute_profile: 1
    compute_resource: controller-02
  identity-01:
    compute_profile: 2
    compute_resource: controller-03
  image-01:
    compute_profile: 2
    compute_resource: controller-02
  logger-01:
    compute_profile: 3
    compute_resource: controller-04
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'masstorage'
          capacity:     '100G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  metric-01:
    compute_profile: 3
    compute_resource: controller-01
  monitor-01:
    compute_profile: 2
    compute_resource: controller-04
  mq-01:
    compute_profile: 1
    compute_resource: controller-01
  nat-linux-01:
    compute_profile: 1
    compute_resource: controller-01
  network-01:
    compute_profile: 2
    compute_resource: controller-03
  network-02:
    compute_profile: 2
    compute_resource: controller-01
  network-03:
    compute_profile: 2
    compute_resource: controller-02
  novactrl-01:
    compute_profile: 2
    compute_resource: controller-02
  object-01:
    mac: d0:94:66:09:0d:6c
    hostgroup: 9
  object-02:
    mac: d0:94:66:09:17:a7
    hostgroup: 9
  object-03:
    mac: d0:94:66:09:53:bc
    hostgroup: 9
  object-04:
    mac: d0:94:66:09:2a:b7
    hostgroup: 9
  object-05:
    mac: d0:94:66:09:41:d5
    hostgroup: 9
  proxy-01:
    compute_profile: 1
    compute_resource: controller-01
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  status-01:
    compute_profile: 1
    compute_resource: controller-02
  storage-01:
    mac: b0:83:fe:cd:64:7c
    hostgroup: 2
  storage-02:
    mac: b0:83:fe:cd:4b:39
    hostgroup: 2
  storage-03:
    mac: b0:83:fe:cd:61:3b
    hostgroup: 2
  storage-04:
    mac: b0:83:fe:cd:61:23
    hostgroup: 2
  storage-05:
    mac: b0:83:fe:cd:44:0f
    hostgroup: 2
  storage-06:
    mac: d0:94:66:19:c2:39
    hostgroup: 2
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'sdg'
  storage-07:
    mac: d0:94:66:19:c1:eb
    hostgroup: 2
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'sdg'
  telemetry-01:
    compute_profile: 3
    compute_resource: controller-03
  volume-01:
    compute_profile: 2
    compute_resource: controller-03
