---
nodes:
  api-01:
    compute_profile:      1
    compute_resource:     'controller-01'
  db-global-01:
    compute_resource:     'controller-01'
    compute_profile:      1
  db-regional-01:
    compute_resource:     'controller-01'
    compute_profile:      1
  dns-01:
    compute_profile: 1
    compute_resource:     'controller-01'
  identity-01:
    compute_resource:     'controller-01'
    compute_profile:      1
  identity-02:
    compute_profile: 1
    compute_resource:     'controller-01'
  image-01:
    compute_resource:     'controller-01'
    compute_profile:      1
  mq-01:
    compute_resource:     'controller-01'
    compute_profile:      1
  network-01:
    compute_resource:     'controller-01'
    compute_profile:      1
  novactrl-01:
    compute_resource:     'controller-01'
    compute_profile:      1
  ns-01:
    compute_profile: 1
    compute_resource:     'controller-01'
  proxy-01:
    compute_resource:     'controller-01'
    compute_profile:      1
  controller-01:
    mac: 00:23:24:5e:34:c8 #1
  compute-01:
    mac: 00:23:24:5e:35:20 #2
  controller-02:
    mac: 00:23:24:5e:35:20 #2
  volume-01:
    compute_resource:     'controller-01'
    compute_profile:      1
