nodes:
  access-01:
    compute_profile: 1
    compute_resource: controller-02
  api-01:
    compute_profile: 1
    compute_resource: controller-01
  builder-01:
    compute_profile: 1
    compute_resource: controller-01
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  compute-01: #8
    mac: 00:23:24:5e:33:b5
  compute-02: #2
    mac: 00:23:24:5e:35:20
  console-01:
    compute_profile: 1
    compute_resource: controller-02
  controller-02: #7
    mac: 00:23:24:5e:32:7e
  dashboard-01:
    compute_profile: 1
    compute_resource: controller-01
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '60G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  db-01:
    compute_profile: 1
    compute_resource: controller-01
  db-02:
    compute_profile: 1
    compute_resource: controller-02
  identity-01:
    compute_profile: 1
    compute_resource: controller-01
  image-01:
    compute_profile: 1
    compute_resource: controller-01
  logger-01:
    compute_profile: 1
    compute_resource: controller-02
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'raw'
      nics_attributes:
        'br1': {}
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  monitor-01:
    compute_profile: 1
    compute_resource: controller-02
    compute_attributes:
      nics_attributes:
        'br1': {}
  mq-01:
    compute_profile: 1
    compute_resource: controller-01
  mq-02:
    compute_profile: 1
    compute_resource: controller-02
  network-01:
    compute_profile: 1
    compute_resource: controller-02
  novactrl-01:
    compute_profile: 2
    compute_resource: controller-02
  proxy-01:
    compute_profile: 1
    compute_resource: controller-01
  volume-01:
    compute_profile: 1
    compute_resource: controller-02
