nodes:
  access-01:
    compute_profile: 1
    compute_resource: controller-03
  api-01:
    compute_profile: 1
    compute_resource: controller-03
  builder-01:
    compute_profile: 2
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  cephmon-01:
    compute_profile: 1
    compute_resource: controller-01
  cephmon-02:
    compute_profile: 1
    compute_resource: controller-02
  cephmon-03:
    compute_profile: 1
    compute_resource: controller-03
  compute-01:
    mac: 00:23:ae:ec:1d:30
  compute-02:
    mac: 78:45:c4:f8:5d:db
  compute-03:
    mac: 00:1e:c9:d1:67:68
  compute-04:
    mac: 00:1e:c9:f6:28:e2
  console-01:
    compute_profile: 1
    compute_resource: controller-03
  controller-02:
    mac: 78:45:c4:f9:ac:8b
  controller-03:
    mac: f8:bc:12:52:d8:68
  dashboard-01:
    compute_profile: 1
    compute_resource: controller-02
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '60G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  db-01:
    compute_profile: 1
    compute_resource: controller-01
  db-02:
    compute_profile: 1
    compute_resource: controller-02
  identity-01:
    compute_profile: 1
    compute_resource: controller-03
  image-01:
    compute_profile: 1
    compute_resource: controller-02
  logger-01:
    compute_profile: 2
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  metric-01:
    compute_profile: 2
    compute_resource: controller-01
  monitor-01:
    compute_profile: 1
    compute_resource: controller-01
  mq-01:
    compute_profile: 1
    compute_resource: controller-01
  nat-linux-01:
    compute_profile: 1
    compute_resource: controller-03
  network-01:
    compute_profile: 1
    compute_resource: controller-03
  network-02:
    compute_profile: 1
    compute_resource: controller-01
  novactrl-01:
    compute_profile: 1
    compute_resource: controller-02
  proxy-01:
    compute_profile: 1
    compute_resource: controller-01
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '20G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  status-01:
    compute_profile: 1
    compute_resource: controller-03
  storage-01:
    mac: d0:67:e5:ef:12:29
  storage-02:
    mac: 00:24:e8:3f:90:e8
  storage-03:
    mac: bc:30:5b:e0:4f:90
  storage-04:
    mac: bc:30:5b:e0:0c:0f
  storage-05:
    mac: bc:30:5b:e0:4e:4f
  telemetry-01:
    compute_profile: 3
    compute_resource: controller-03
  volume-01:
    compute_profile: 1
    compute_resource: controller-03
  ns-01:
    compute_profile: 1
    compute_resource: controller-01
  resolver-01:
    compute_profile: 1
    compute_resource: controller-02
  resolver-02:
    compute_profile: 1
    compute_resource: controller-03
