nodes:
  access-01:
    compute_profile: small
    compute_resource: controller-01
  api-01:
    compute_profile: small
    compute_resource: controller-01
  admin-01:
    compute_profile: small
    compute_resource: controller-03
  builder-01:
    compute_profile: medium
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'masstorage'
          capacity:     '50G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  cephmon-01:
    compute_profile: large
    compute_resource: controller-01
  cephmon-02:
    compute_profile: large
    compute_resource: controller-02
  cephmon-03:
    compute_profile: large
    compute_resource: controller-03
  compute-01:
    mac: 00:24:e8:38:a4:19
    hostgroup: 3
  compute-02:
    mac: b8:ac:6f:86:b6:6d
    hostgroup: 3
  compute-03:
    mac: b8:ac:6f:91:62:ed
    hostgroup: 3
  console-01:
    compute_profile: small
    compute_resource: controller-02
  controller-02:
    mac: b8:ac:6f:91:8c:ab
  controller-03:
    mac: b8:ac:6f:8d:3a:54
  dashboard-01:
    compute_profile: small
    compute_resource: controller-02
  dashboard-mgmt-01:
    compute_profile: small
    compute_resource: controller-03
  db-global-01:
    compute_profile: small
    compute_resource: controller-02
  db-regional-01:
    compute_profile: medium
    compute_resource: controller-01
  dns-01:
    compute_profile: small
    compute_resource: controller-02
  identity-01:
    compute_profile: small
    compute_resource: controller-01
  identity-02:
    compute_profile: small
    compute_resource: controller-02
  image-01:
    compute_profile: small
    compute_resource: controller-01
  image-02:
    compute_profile: small
    compute_resource: controller-02
  logger-01:
    compute_profile: medium
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'masstorage'
          capacity:     '100G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  metric-01:
    compute_profile: xlarge
    compute_resource: controller-01
  monitor-01:
    compute_profile: small
    compute_resource: controller-03
  mq-01:
    compute_profile: medium
    compute_resource: controller-01
  nat-01:
    compute_profile: small
    hostgroup: 4
    compute_resource: controller-01
  network-01:
    compute_profile: small
    compute_resource: controller-01
  network-02:
    compute_profile: small
    compute_resource: controller-02
  network-03:
    compute_profile: small
    compute_resource: controller-03
  novactrl-01:
    compute_profile: medium
    compute_resource: controller-01
  novactrl-02:
    compute_profile: medium
    compute_resource: controller-02
  nfs-01:
    compute_profile: small
    compute_resource: controller-03
  ns-01:
    compute_profile: small
    compute_resource: controller-01
  proxy-01:
    compute_profile: small
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'masstorage'
          capacity:     '50G'
          format_type:  'qcow2'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  resolver-01:
    compute_profile: small
    compute_resource: controller-02
  resolver-02:
    compute_profile: small
    compute_resource: controller-03
  status-01:
    compute_profile: small
    compute_resource: controller-02
  storage-01:
    mac: 00:24:e8:2e:e3:9d
    hostgroup: 2
  storage-02:
    mac: 00:26:b9:7d:15:3a
    hostgroup: 2
  storage-03:
    mac: b8:ac:6f:8a:94:af
    hostgroup: 2
  storage-04:
    mac: b8:ac:6f:80:f1:b0
    hostgroup: 2
  storage-05:
    mac: 00:26:b9:79:1a:ce
    hostgroup: 2
  telemetry-01:
    compute_profile: xlarge
    compute_resource: controller-03
  volume-01:
    compute_profile: small
    compute_resource: controller-01
  volume-02:
    compute_profile: small
    compute_resource: controller-02
  workflow-01:
    compute_profile: small
    compute_resource: controller-03
