nodes:
  access-01:
    compute_profile: small
    compute_resource: controller-03
  api-01:
    compute_profile: small
    compute_resource: controller-03
  builder-01:
    compute_profile: medium
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  cephmds-01:
    compute_profile: small
    compute_resource: controller-01
  cephmds-02:
    compute_profile: small
    compute_resource: controller-02
  cephmds-03:
    compute_profile: small
    compute_resource: controller-03
  cephmon-01:
    compute_profile: small
    compute_resource: controller-01
  cephmon-02:
    compute_profile: small
    compute_resource: controller-02
  cephmon-03:
    compute_profile: small
    compute_resource: controller-03
  compute-01:
    hostgroup: 3
    mac: 00:23:ae:ec:1d:30
  compute-02:
    hostgroup: 3
    mac: 78:45:c4:f8:5d:db
  compute-03:
    hostgroup: 3
    mac: 84:2b:2b:ff:f0:8c
  compute-04:
    hostgroup: 3
    mac: 84:2b:2b:ff:f0:fc
  console-01:
    compute_profile: small
    compute_resource: controller-03
  controller-02:
    mac: 78:45:c4:f9:ac:8b
  controller-03:
    mac: f8:bc:12:52:d8:68
  dashboard-01:
    compute_profile: small
    compute_resource: controller-02
  dashboard-mgmt-01:
    compute_profile: small
    compute_resource: controller-03
  db-global-01:
    compute_profile: small
    compute_resource: controller-02
  db-regional-01:
    compute_profile: medium
    compute_resource: controller-01
  dns-01:
    compute_profile: small
    compute_resource: controller-02
  identity-01:
    compute_profile: small
    compute_resource: controller-01
  identity-02:
    compute_profile: small
    compute_resource: controller-02
  image-01:
    compute_profile: small
    compute_resource: controller-01
  image-02:
    compute_profile: small
    compute_resource: controller-02
  logger-01:
    compute_profile: medium
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '100G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  metric-01:
    compute_profile: medium
    compute_resource: controller-01
  monitor-01:
    compute_profile: small
    compute_resource: controller-01
  mq-01:
    compute_profile: medium
    compute_resource: controller-01
  nat-linux-01:
    compute_profile: small
    compute_resource: controller-03
  network-01:
    compute_profile: small
    compute_resource: controller-01
  network-02:
    compute_profile: small
    compute_resource: controller-02
  network-03:
    compute_profile: small
    compute_resource: controller-03
  novactrl-01:
    compute_profile: medium
    compute_resource: controller-01
  novactrl-02:
    compute_profile: medium
    compute_resource: controller-02
  ns-01:
    compute_profile: small
    compute_resource: controller-01
  proxy-01:
    compute_profile: small
    compute_resource: controller-03
    compute_attributes:
      volumes_attributes:
        '1':
          allocation:   '0G'
          pool_name:    'dirpool'
          capacity:     '50G'
          format_type:  'raw'
    host_parameters_attributes:
      - name:           'installdevice'
        value:          'vda'
  resolver-01:
    compute_profile: small
    compute_resource: controller-02
  resolver-02:
    compute_profile: small
    compute_resource: controller-03
  status-01:
    compute_profile: small
    compute_resource: controller-03
  storage-01:
    hostgroup: 2
    mac: d0:67:e5:ef:12:29
  storage-02:
    hostgroup: 2
    mac: 00:24:e8:3f:90:e8
  storage-03:
    hostgroup: 2
    mac: bc:30:5b:e0:4f:90
  storage-04:
    hostgroup: 2
    mac: bc:30:5b:e0:0c:0f
  storage-05:
    hostgroup: 2
    mac: bc:30:5b:e0:4e:4f
  telemetry-01:
    compute_profile: xlarge
    compute_resource: controller-03
  volume-01:
    compute_profile: small
    compute_resource: controller-01
  volume-02:
    compute_profile: small
    compute_resource: controller-02
